# Generated by Django 5.2.17 on 2026-08-14 12:55

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-publish_time', '-pk'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='发布状态'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_published', '-publish_time'], name='item_pub_time_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_published', '-publish_time'], name='item_cat_pub_time_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='item_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
