# Generated by Django 5.2.17 on 2026-08-14

import django.contrib.postgres.indexes
from django.db import migrations
from django.db.models import Q
from django.db.models.functions import Upper


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("content", "0002_postgresql_constraints_indexes"),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveIndex(
            model_name="item",
            name="item_title_trgm_idx",
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(Upper("title"), name="gin_trgm_ops"),
                condition=Q(is_published=True),
                name="item_title_trgm_idx",
            ),
        ),
    ]
